name: deploy
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 校验
      - name: Checkout
        uses:
          actions/checkout@v3
      - name:
        run: 
          echo "checkout执行完成"

          # 构建
      - name: Install and Build
        uses: actions/setup-node@master
        with:
          node-version: "20.x"
      - name: 
        run: 
          echo "构建完成"

        # 部署
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-master
          publish_dir: ./dist
          github_token: ${{secrets.TRENDEXC}}
          user_name: ${{secrets.MY_USER_NAME}}
          user_email: ${{secrets.MY_USER_EMAIL}}
          commit_message: CICD自动部署
      - name: 
        run: |
          echo(${{secrets.MY_USER_NAME}})
          echo("部署完成")
